### ISSUE TITLE
support 1.19.4?

### ISSUE THREAD

**Issue by adalmo** [SkytAsul/JukeBox#45]
[12:21:39 ERROR]: Error occurred while enabling JukeBox v1.20.8 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because the return value of "com.xxmicloxx.NoteBlockAPI.model.Song.getPath()" is null
        at fr.skytasul.music.JukeBox.getInternal(JukeBox.java:451) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.JukeBox.loadDatas(JukeBox.java:290) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.JukeBox.initAll(JukeBox.java:224) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.JukeBox.onEnable(JukeBox.java:129) ~[jukebox-1.20.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:569) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:480) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:642) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:344) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1119) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.19.4.jar:git-Purpur-1946]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[12:21:39 INFO]: [JukeBox] Disabling JukeBox v1.20.8

**Comment by SkytAsul** [comment]
Which version of NoteBlockAPI are you using.

**Comment by adalmo** [comment]
2.0 SNAPSHOT With latest build #11

**Comment by SkytAsul** [comment]
I think it's a problem with NBAPI. It works well with 1.6.1. Ask NBAPI dev.

**Comment by SkytAsul** [comment]
Got no answer
