### ISSUE TITLE
java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.EntityPlayer

### ISSUE THREAD

**Issue by cwchristerw** [SkytAsul/JukeBox#47]
[17:59:32 INFO]: [JukeBox] Enabling JukeBox v1.20.8
[17:59:32 INFO]: [JukeBox] Placeholders registered
[17:59:32 INFO]: [JukeBox] This JukeBox version requires NoteBlockAPI version 1.5.0 or more. Please ensure you have the right version before using JukeBox (you are using NBAPI ver. 1.6.2-SNAPSHOT)
[17:59:32 WARN]: [JukeBox] Found 4 inexistant string(s) in en.yml: SHUFFLE_MODE LOOP_MODE CONNEXION_MUSIC PARTICLES
[17:59:32 INFO]: [JukeBox] Loaded language file en.yml
[17:59:32 INFO]: [JukeBox] Connected to database.
[17:59:35 INFO]: [JukeBox] 263 songs loadeds. Sorting by name... 
[17:59:36 INFO]: [JukeBox] Songs sorted ! 263 songs. Number of pages : 6
[17:59:36 WARN]:  java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R3.EntityPlayer
[17:59:36 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
[17:59:36 WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
[17:59:36 WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[17:59:36 WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[17:59:36 WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[17:59:36 WARN]: 	at jukebox-1.20.8.jar//fr.skytasul.music.JukeBox.getVersionedClass(JukeBox.java:252)
[17:59:36 WARN]: 	at jukebox-1.20.8.jar//fr.skytasul.music.JukeBox.initAll(JukeBox.java:233)
[17:59:36 WARN]: 	at jukebox-1.20.8.jar//fr.skytasul.music.JukeBox.onEnable(JukeBox.java:129)
[17:59:36 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279)
[17:59:36 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[17:59:36 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:59:36 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:59:36 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:555)
[17:59:36 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:466)
[17:59:36 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[17:59:36 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[17:59:36 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[17:59:36 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[17:59:36 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:59:36 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by SkytAsul** [comment]
Yeah JukeBox is completely outdated... you can disable the "preventVanillaMusic" option in config.yml.

**Comment by cwchristerw** [comment]
It worked
