### ISSUE TITLE
java.sql.SQLException: Unknown system variable 'transaction_isolation'

### ISSUE THREAD

**Issue by cwchristerw** [SkytAsul/JukeBox#48]
[21:04:52 WARN]: java.sql.SQLException: Unknown system variable 'transaction_isolation'
[21:04:52 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[21:04:52 WARN]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[21:04:52 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824)
[21:04:52 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)
[21:04:52 WARN]: 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237)
[21:04:52 WARN]: 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
[21:04:52 WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
[21:04:52 WARN]: 	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190)
[21:04:52 WARN]: 	at jukebox-1.20.8.jar//fr.skytasul.music.utils.Database.openConnection(Database.java:51)
[21:04:52 WARN]: 	at jukebox-1.20.8.jar//fr.skytasul.music.JukeBox.initAll(JukeBox.java:207)
[21:04:52 WARN]: 	at jukebox-1.20.8.jar//fr.skytasul.music.JukeBox.onEnable(JukeBox.java:129)
[21:04:52 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[21:04:52 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[21:04:52 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[21:04:52 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[21:04:52 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[21:04:52 WARN]: 	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[21:04:52 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[21:04:52 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[21:04:52 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[21:04:52 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[21:04:52 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:04:52 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by cwchristerw** [comment]
This is because I use latest MariaDB which is not compatible with MySQL Connector

**Comment by cwchristerw** [comment]
https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html
The tx_isolation and tx_read_only system variables have been removed. Use transaction_isolation and transaction_read_only instead.

**Comment by cwchristerw** [comment]
I would suggest that we should add support to change between mysql and mariadb.

**Comment by cwchristerw** [comment]
This was caused by MySQL JDBC closing issue fixed by updating to MariaDB version 11.1.1 RC

**Comment by SkytAsul** [comment]
Thanks for the detailed explanations!
