### ISSUE TITLE
Plugin doesnt enable on 1.20.2

### ISSUE THREAD

**Issue by Budderman18** [SkytAsul/JukeBox#49]
Plugin disabled with this:

Error occurred while enabling JukeBox v1.20.8 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at fr.skytasul.music.utils.Playlists.item(Playlists.java:35) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.utils.Playlists.<clinit>(Playlists.java:11) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.PlayerData.<init>(PlayerData.java:41) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.PlayerData.deserialize(PlayerData.java:483) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.JukeBox.initAll(JukeBox.java:172) ~[jukebox-1.20.8.jar:?]
        at fr.skytasul.music.JukeBox.onEnable(JukeBox.java:129) ~[jukebox-1.20.8.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.2.jar:git-Paper-217]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-217]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644) ~[paper-1.20.2.jar:git-Paper-217]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555) ~[paper-1.20.2.jar:git-Paper-217]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-217]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-217]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-217]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-217]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-217]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Profile name must not be null
        at java.util.Objects.requireNonNull(Objects.java:259) ~[?:?]
        at com.mojang.authlib.GameProfile.<init>(GameProfile.java:31) ~[authlib-5.0.47.jar:?]
        at fr.skytasul.music.JukeBoxInventory.<clinit>(JukeBoxInventory.java:358) ~[jukebox-1.20.8.jar:?]
        ... 18 more

**Comment by SkytAsul** [comment]
Fixed with https://github.com/SkytAsul/JukeBox/commit/4d31fc964b97bff95f172cea3a52dc49a2d37a08
