### ISSUE TITLE
Jukebox spams errors in 1.18.2

### ISSUE THREAD

**Issue by CityPvP** [SkytAsul/JukeBox#57]
When im using /jukebox manually:

```
[15:52:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'jukebox' in plugin JukeBox v1.20.11
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
        at fr.skytasul.music.JukeBoxInventory.openInventory(JukeBoxInventory.java:76) ~[jukebox-1.20.11.jar:?]
        at fr.skytasul.music.CommandMusic.open(CommandMusic.java:35) ~[jukebox-1.20.11.jar:?]
        at fr.skytasul.music.CommandMusic.onCommand(CommandMusic.java:20) ~[jukebox-1.20.11.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 21 more
>
```

And This Happens when i force a player executing it with skript (make player execute command "jukebox")

```
[15:51:14 WARN]: org.bukkit.command.CommandException: Unhandled exception executing command 'jukebox' in plugin JukeBox v1.20.11
[15:51:14 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47)
[15:51:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[15:51:14 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[15:51:14 WARN]:        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:959)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.Skript.dispatchCommand(Skript.java:1509)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.effects.EffCommand.execute(EffCommand.java:102)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.lang.Effect.run(Effect.java:49)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:61)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.lang.Trigger.execute(Trigger.java:52)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$2(SkriptEventHandler.java:183)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.lambda$execute$3(SkriptEventHandler.java:194)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:164)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.util.Task.callSync(Task.java:148)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.execute(SkriptEventHandler.java:192)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:138)
[15:51:14 WARN]:        at Skript.jar//ch.njol.skript.SkriptEventHandler$PriorityListener.lambda$new$0(SkriptEventHandler.java:64)
[15:51:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[15:51:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:51:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[15:51:14 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544)
[15:51:14 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507)
[15:51:14 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502)
[15:51:14 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498)
[15:51:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1984)
[15:51:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28)
[15:51:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[15:51:14 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[15:51:14 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:51:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:51:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1427)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[15:51:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1404)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1397)
[15:51:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1375)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1257)
[15:51:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[15:51:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[15:51:14 WARN]: Caused by: java.lang.IncompatibleClassChangeError: Found class org.bukkit.inventory.InventoryView, but interface was expected
[15:51:14 WARN]:        at jukebox-1.20.11.jar//fr.skytasul.music.JukeBoxInventory.openInventory(JukeBoxInventory.java:76)
[15:51:14 WARN]:        at jukebox-1.20.11.jar//fr.skytasul.music.CommandMusic.open(CommandMusic.java:35)
[15:51:14 WARN]:        at jukebox-1.20.11.jar//fr.skytasul.music.CommandMusic.onCommand(CommandMusic.java:20)
[15:51:14 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[15:51:14 WARN]:        ... 40 more
```

**Comment by SkytAsul** [comment]
Use version 1.20.10
